tweetstream-and-zeitgeist:
    id: tweetstream_and_zeitgeist
    title: "Tweetstream and Zeitgeist in: On the Scene!"
    image: https://c2.staticflickr.com/2/1695/26353066916_2651cca279_b.jpg
    description: |
        Twitter and Google's very own superheroes use social media to help them in their crusading for justice.
    parts:
      -
        title: "Part 1/3"
        panels:
          - "https://c2.staticflickr.com/2/1477/25776230233_344be0d85c_b.jpg"
          - "https://c2.staticflickr.com/2/1695/26353066916_2651cca279_b.jpg"
          - "https://c2.staticflickr.com/2/1647/26378954795_5104f9488c_b.jpg"
          - "https://c2.staticflickr.com/2/1501/26286622732_1ca5e52d0d_b.jpg"
          - "https://c2.staticflickr.com/2/1715/26378954755_7e40469d13_b.jpg"
          - "https://c2.staticflickr.com/2/1468/26286622712_89bc6e1a2f_b.jpg"
          - "https://c2.staticflickr.com/2/1598/26286622682_01fcbfe8af_b.jpg"
          - "https://c2.staticflickr.com/2/1634/26353066816_bc6e124edc_b.jpg"
      -
        title: "Part 2/3"
        panels:
          - "https://c2.staticflickr.com/2/1464/26353066776_8565311a2b_b.jpg"
          - "https://c2.staticflickr.com/2/1565/26286622592_cb9ee02c74_b.jpg"
          - "https://c2.staticflickr.com/2/1605/26353066726_96b6c6d389_b.jpg"
          - "https://c2.staticflickr.com/2/1683/26353066686_311a5925d3_b.jpg"
          - "https://c2.staticflickr.com/2/1596/25776229933_d23d50530b_b.jpg"
          - "https://c2.staticflickr.com/2/1523/26353066636_2bb1670acd_b.jpg"
          - "https://c2.staticflickr.com/2/1665/25774131634_59112d2640_b.jpg"
          - "https://c2.staticflickr.com/2/1696/26286622472_63cd1752fc_b.jpg"
          - "https://c2.staticflickr.com/2/1707/26106128770_5e9e9e041c_b.jpg"
      -
        title: "Part 3/3"
        panels:
          - "https://c2.staticflickr.com/2/1582/26378954445_9be891e92c_b.jpg"
          - "https://c2.staticflickr.com/2/1622/26286622432_bd04d5715d_b.jpg"
          - "https://c2.staticflickr.com/2/1607/26286622382_5d12a1d7a9_b.jpg"
          - "https://c2.staticflickr.com/2/1703/25776229693_74e47efd1d_b.jpg"
