panel:
  width: 1920
  height: 1080
objects:
  -
    id: "container"
    location:
      top: 0
      left: 0
    dimensions:
      width: 1920
      height: 3990
  -
    id: "intro_hydrant"
    image_url: "/img/intro_hydrant.jpg"
    location:
      top: 41
      left: 309
    dimensions:
      width: 1301
      height: 756
    classes:
      - img-round-corners
  -
    id: "intro_shoes"
    image_url: "/img/intro_shoes.png"
    location:
      top: 0
      left: 1219
    dimensions:
      width: 377
      height: 583
  -
    id: "intro_signature"
    image_url: "/img/intro_signature.png"
    location:
      top: 0
      left: 36
    dimensions:
      width: 893
      height: 381
    parallax:
      parallax_id: intro_signature_parallax
      scale: 0.04
  -
    id: "intro_tagline"
    image_url: "/img/intro_tagline.png"
    location:
      top: 460
      left: 1060
    dimensions:
      width: 592
      height: 368
    parallax:
      parallax_id: intro_tagline_parallax
      scale: 0.015
  -
    id: "great_button"
    location:
      top: 672
      left: 857
    button:
      text: "Great!"
    classes:
      - btn
      - btn-success
  -
    id: "portfolio_background"
    image_url: "/img/portfolio_background.jpg"
    location:
      top: 863
      left: 0
    dimensions:
      width: 1919
      height: 1024
    classes:
      - img-round-corners
  -
    id: "portfolio_arrows"
    image_url: "/img/portfolio_arrows.png"
    location:
      top: 867
      left: 472
    dimensions:
      width: 557
      height: 405
  -
    id: "portfolio_title_parallax02"
    image_url: "/img/portfolio_title_parallax02.png"
    location:
      top: 855
      left: 175
    dimensions:
      width: 273
      height: 83
    parallax:
      parallax_id: portfolio_parallax
      scale: 0.05
  -
    id: "portfolio_title_parallax01"
    image_url: "/img/portfolio_title_parallax01.png"
    location:
      top: 850
      left: 169
    dimensions:
      width: 288
      height: 87
    parallax:
      parallax_id: portfolio_parallax
      scale: 0.025
  -
    id: "portfolio_title"
    image_url: "/img/portfolio_title.png"
    location:
      top: 846
      left: 161
    dimensions:
      width: 303
      height: 91
  -
    id: "portfolio_trigger_gallery_swap"
    image_url: "/img/portfolio_trigger_gallery_hover.png"
    location:
      top: 875
      left: 865
    dimensions:
      width: 116
      height: 39
    hidden: true
  -
    id: "portfolio_trigger_instagram_swap"
    image_url: "/img/portfolio_trigger_instagram_hover.png"
    location:
      top: 875
      left: 692
    dimensions:
      width: 140
      height: 39
    hidden: true
  -
    id: "portfolio_trigger_comics_swap"
    image_url: "/img/portfolio_trigger_comics_hover.png"
    location:
      top: 1131
      left: 705
    dimensions:
      width: 91
      height: 39
    hidden: true
  -
    id: "portfolio_trigger_gallery"
    image_url: "/img/portfolio_trigger_gallery.png"
    alt: "Regular Gallery"
    location:
      top: 875
      left: 875
    dimensions:
      width: 116
      height: 39
    hover_swap:
      swap_image_src: "/img/portfolio_trigger_gallery_hover.png"
    slides_gallery_trigger:
      swap_image_src: "/img/portfolio_trigger_gallery_hover.png"
    click_scroll:
      scroll_y: 825
      duration: 1
  -
    id: "portfolio_trigger_instagram"
    image_url: "/img/portfolio_trigger_instagram.png"
    alt: "Instagram Gallery"
    location:
      top: 875
      left: 692
    dimensions:
      width: 140
      height: 39
    hover_swap:
      swap_image_src: "/img/portfolio_trigger_instagram_hover.png"
    slides_gallery_trigger:
      swap_image_src: "/img/portfolio_trigger_instagram_hover.png"
    click_scroll:
      scroll_y: 825
      duration: 1
  -
    id: "portfolio_trigger_comics"
    image_url: "/img/portfolio_trigger_comics.png"
    alt: "Comics Gallery"
    location:
      top: 1131
      left: 705
    dimensions:
      width: 91
      height: 39
    hover_swap:
      swap_image_src: "/img/portfolio_trigger_comics_hover.png"
    slides_gallery_trigger:
      swap_image_src: "/img/portfolio_trigger_comics_hover.png"
    click_scroll:
      scroll_y: 825
      duration: 1
  -
    id: "portfolio_neonsign01"
    image_url: "/img/portfolio_neonsign01.png"
    location:
      top: 1650
      left: 78
    dimensions:
      width: 174
      height: 214
    flicker:
      delay: 1
      min_duration: 0.05
      max_duration: 0.5
      min_opacity: 0.2
      max_opacity: 0.9
  -
    id: "portfolio_neonsign02"
    image_url: "/img/portfolio_neonsign02.png"
    location:
      top: 1513
      left: 257
    dimensions:
      width: 214
      height: 244
    flicker:
      delay: 1
      min_duration: 0.05
      max_duration: 0.5
      min_opacity: 0.2
      max_opacity: 0.9
  -
    id: "portfolio_gallery_regular_container"
    location:
      top: 914
      left: 0
    dimensions:
      width: 1919
      height: 915
    container:
      id: portfolio_gallery_regular
      view_script: "partials/index/portfolio_gallery_regular.twig.html"
    slides_gallery:
      id: portfolio_gallery_regular
      trigger_id: portfolio_trigger_gallery
  -
    id: "portfolio_gallery_instagram_container"
    location:
      top: 914
      left: 0
    dimensions:
      width: 1919
      height: 915
    container:
      id: portfolio_gallery_instagram
      view_script: "partials/index/portfolio_gallery_instagram.twig.html"
    slides_gallery:
      id: portfolio_gallery_instagram
      trigger_id: portfolio_trigger_instagram
  -
    id: "portfolio_gallery_comics_container"
    location:
      top: 914
      left: 0
    dimensions:
      width: 1919
      height: 915
    container:
      id: portfolio_gallery_comics
      view_script: "partials/index/portfolio_gallery_comics.twig.html"
    slides_gallery:
      id: portfolio_gallery_comics
      trigger_id: portfolio_trigger_comics
  -
    id: "whatido_background"
    image_url: "/img/whatido_background.jpg"
    location:
      top: 2016
      left: 203
    dimensions:
      width: 1514
      height: 862
    classes:
      - img-round-corners
  -
    id: "whatido_title_parallax02"
    image_url: "/img/whatido_title_parallax02.png"
    location:
      top: 1942
      left: 185
    dimensions:
      width: 394
      height: 101
    parallax:
      parallax_id: whatido_parallax
      scale: 0.05
  -
    id: "whatido_title_parallax01"
    image_url: "/img/whatido_title_parallax01.png"
    location:
      top: 1939
      left: 174
    dimensions:
      width: 416
      height: 107
    parallax:
      parallax_id: whatido_parallax
      scale: 0.025
  -
    id: "whatido_title"
    image_url: "/img/whatido_title.png"
    location:
      top: 1936
      left: 163
    dimensions:
      width: 438
      height: 113
  -
    id: "whatido_copy"
    container:
      id: whatido_copy_markup
      view_script: "partials/index/whatido_copy.twig.html"
    location:
      top: 2016
      left: 203
    dimensions:
      width: 1514
      height: 862
  -
    id: "info_background"
    image_url: "/img/info_background.jpg"
    location:
      top: 3046
      left: 226
    dimensions:
      width: 1433
      height: 897
    classes:
      - img-round-corners
  -
    id: "info_title_parallax02"
    image_url: "/img/info_title_parallax02.png"
    location:
      top: 2987
      left: 183
    dimensions:
      width: 357
      height: 134
    parallax:
      parallax_id: info_parallax
      scale: 0.05
  -
    id: "info_title_parallax01"
    image_url: "/img/info_title_parallax01.png"
    location:
      top: 2983
      left: 173
    dimensions:
      width: 377
      height: 140
    parallax:
      parallax_id: info_parallax
      scale: 0.025
  -
    id: "info_title"
    image_url: "/img/info_title.png"
    location:
      top: 2977
      left: 163
    dimensions:
      width: 397
      height: 148
  -
    id: "info_copy"
    container:
      id: info_copy_markup
      view_script: "partials/index/info_copy.twig.html"
    location:
      top: 3046
      left: 226
    dimensions:
      width: 1433
      height: 897

parallax:
  -
    id: intro_signature_parallax
    location:
      left: 530
      top: 230
  -
    id: intro_tagline_parallax
    location:
      left: 1358
      top: 678
  -
    id: portfolio_parallax
    location:
      left: 310
      top: 904
  -
    id: whatido_parallax
    location:
      left: 398
      top: 2010
  -
    id: info_parallax
    location:
      left: 348
      top: 3069
